
title: Zeyang Ma's Website
page-top-title: Zeyang Ma
home-role: 'Ph.D. Candidate · Concordia University'
copyright-text: '&copy; Zeyang Ma 2026. All Rights Reserved.'
last-updated-text: 'Last updated: September 2026'
