const fs = require('node:fs');
const path = require('node:path');
const marked = require('../static/js/marked.min.js');
const yaml = require('../static/js/js-yaml.min.js');

const root = path.resolve(__dirname, '..');

function renderSite(directory = root) {
    const read = file => fs.readFileSync(path.join(directory, file), 'utf8');
    const config = yaml.load(read('contents/config.yml'));
    if (!config || typeof config !== 'object' || Array.isArray(config)) {
        throw new Error('contents/config.yml must contain a mapping.');
    }

    const usedConfig = new Set();
    const template = read('templates/index.html');
    // Only trusted, repository-owned content is rendered; HTML in Markdown is intentional.
    const rendered = template.replace(/\{\{\s*(config|content|script):([a-z][a-z0-9-]*)\s*\}\}/g, (_, kind, name) => {
        if (kind === 'script') return read(`static/js/${name}.js`).trim();
        const id = kind === 'config' ? name : `${name}-md`;
        if (!template.includes(`id="${id}"`)) {
            throw new Error(`Missing DOM id for ${kind}:${name}`);
        }
        if (kind === 'content') {
            return marked.parse(read(`contents/${name}.md`), { mangle: false, headerIds: false }).trim();
        }
        if (!Object.hasOwn(config, name) || typeof config[name] !== 'string') {
            throw new Error(`Missing or non-string config value: ${name}`);
        }
        usedConfig.add(name);
        return config[name];
    });
    for (const key of Object.keys(config)) {
        if (!usedConfig.has(key)) throw new Error(`Unused config key: ${key}`);
    }
    if (/\{\{\s*(config|content|script):/.test(rendered)) {
        throw new Error('Unresolved template placeholder.');
    }

    // Preserve the site's external-link behavior without needing JavaScript at runtime.
    const html = rendered.replace(/<a\b[^>]*>/gi, tag => {
        if (!/\bhref\s*=\s*(["'])https?:\/\/[^"']*\1/i.test(tag)) return tag;
        return tag.replace(/\s+(?:target|rel)\s*=\s*(?:"[^"]*"|'[^']*')/gi, '')
            .replace(/>$/, ' target="_blank" rel="noopener noreferrer">');
    });
    return html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by node scripts/build.cjs. Edit templates/index.html and contents/ instead. -->');
}

if (require.main === module) {
    try {
        const html = renderSite();
        const output = path.join(root, 'index.html');
        if (process.argv.includes('--check')) {
            if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== html) {
                throw new Error('index.html is out of date. Run node scripts/build.cjs.');
            }
            console.log('Generated index.html is up to date.');
        } else {
            fs.writeFileSync(output, html);
            console.log('Generated index.html.');
        }
    } catch (error) {
        console.error(error.message);
        process.exitCode = 1;
    }
}

module.exports = { renderSite };
